# Generated by Django 3.1.8 on 2021-04-06 09:20

from django.db import migrations, models
import django.utils.timezone
import app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('kana', models.CharField(default='', max_length=200)),
                ('tel1', models.CharField(default='', max_length=11)),
                ('organization', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('tel2', models.CharField(default='', max_length=11)),
                ('prefectures', models.CharField(default='', max_length=8)),
                ('scale', models.CharField(default='', max_length=50)),
                ('others', models.CharField(default='', max_length=10000)),
                ('approval', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to=app.models.getuploadpath)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
