# Generated by Django 3.2 on 2021-04-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='token',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
