# Generated by Django 3.2 on 2021-04-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210407_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
        migrations.AddField(
            model_name='member',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
