# Generated by Django 3.2 on 2021-04-12 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_csv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='document',
            new_name='csv',
        ),
        migrations.AddField(
            model_name='csv',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
