# Generated by Django 3.2 on 2021-04-12 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210412_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
