# Generated by Django 3.2 on 2021-04-12 18:15

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_member_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(upload_to=app.models.getuploadpath),
        ),
    ]
