# Generated by Django 3.2.2 on 2021-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_csv_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
