# Generated by Django 3.2.2 on 2021-05-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_member_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='kana',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='tel1',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='member',
            name='tel2',
            field=models.CharField(default='', max_length=11),
        ),
    ]
