# Generated by Django 3.2.2 on 2021-05-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210513_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mail',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
